url: http://www.kwatra.tech
# baseurl: /
theme: agency-jekyll-theme

# Settings
title: Kabir Kwatra's Portfolio
email: kabir@kwatra.tech
description: "Photography Portfolio"

# Social
people:
  name: Kabir Kwatra
  
